function initial = calculate_integrated_initial_conditions(module, sizing, ...
    firstCurve, boost, inverter, mppt)
%CALCULATE_INTEGRATED_INITIAL_CONDITIONS Engineering equilibrium estimate.
%   Initializes the system near the first irradiance-level MPP without
%   attempting a nonlinear equilibrium solve.

pvVoltage_V = firstCurve.Vmp_V * sizing.series_module_count;
pvCurrent_A = firstCurve.Imp_A * sizing.parallel_string_count;
pvPower_W = pvVoltage_V * pvCurrent_A;
dcVoltage_V = inverter.dc_link_voltage_ref_V;
duty = 1 - pvVoltage_V / dcVoltage_V;
duty = min(max(duty, boost.duty_min), boost.duty_max);
gridPhasePeak_V = sqrt(2) * inverter.grid_voltage_ll_rms_V / sqrt(3);
gridCurrentD_A = pvPower_W / (1.5 * gridPhasePeak_V);

initial = struct( ...
    "pv_voltage_V", pvVoltage_V, ...
    "pv_reference_V", pvVoltage_V + ...
        mppt.perturb_step_V * sizing.series_module_count, ...
    "boost_inductor_current_A", pvCurrent_A, ...
    "dc_link_voltage_V", dcVoltage_V, ...
    "duty_ratio", duty, ...
    "grid_current_d_A", gridCurrentD_A, ...
    "grid_current_q_A", inverter.iq_ref_A, ...
    "initial_pv_power_W", pvPower_W);
end
