function simulation = simulate_integrated_pv_grid_system(module, sizing, ...
    mppt, boost, inverter, system, initial)
%SIMULATE_INTEGRATED_PV_GRID_SYSTEM Couple PV, Boost, DC link, and grid VSI.
%   Existing STEP 2-5 calculation and controller functions are reused. The
%   shared DC capacitor is charged by Boost output current and discharged by
%   averaged inverter DC power. No temporary DC load/source is present.

arguments
    module (1,1) struct
    sizing (1,1) struct
    mppt (1,1) struct
    boost (1,1) struct
    inverter (1,1) struct
    system (1,1) struct
    initial (1,1) struct
end
validateParameters(system, boost, inverter);

time_s = (0:system.sample_time_s:system.simulation_time_s).';
sampleCount = numel(time_s);
segmentCount = numel(system.irradiance_levels_Wm2);
mpptUpdateSamples = round(system.mppt_update_period_s / system.sample_time_s);
omega_rad_s = 2*pi*inverter.grid_frequency_Hz;
gridAngle_rad = omega_rad_s .* time_s;
gridVoltageD_V = sqrt(2) * inverter.grid_voltage_ll_rms_V / sqrt(3);
gridVoltageQ_V = 0.0;

referenceCurves = cell(1, segmentCount);
for segmentIndex = 1:segmentCount
    referenceCurves{segmentIndex} = calculate_pv_module_iv( ...
        module, system.irradiance_levels_Wm2(segmentIndex), ...
        system.temperature_C, system.iv_voltage_point_count);
end
[irradiance_Wm2, curveIndex, theoreticalVmpp_V, theoreticalPmpp_W] = ...
    buildReferenceSignals(time_s, referenceCurves, sizing, system);

pvVoltage_V = zeros(sampleCount, 1);
pvReference_V = zeros(sampleCount, 1);
pvCurrent_A = zeros(sampleCount, 1);
pvPower_W = zeros(sampleCount, 1);
dutyRatio = zeros(sampleCount, 1);
boostCurrent_A = zeros(sampleCount, 1);
boostOutputPower_W = zeros(sampleCount, 1);
dcVoltage_V = zeros(sampleCount, 1);
gridCurrentD_A = zeros(sampleCount, 1);
gridCurrentQ_A = zeros(sampleCount, 1);
gridCurrentDReference_A = zeros(sampleCount, 1);
gridCurrentQReference_A = repmat(inverter.iq_ref_A, sampleCount, 1);
inverterVoltageD_V = zeros(sampleCount, 1);
inverterVoltageQ_V = zeros(sampleCount, 1);
inverterDcPower_W = zeros(sampleCount, 1);
gridActivePower_W = zeros(sampleCount, 1);
gridReactivePower_var = zeros(sampleCount, 1);
modulationMagnitude = zeros(sampleCount, 1);
inverterVoltageSaturated = false(sampleCount, 1);

pvVoltage_V(1) = initial.pv_voltage_V;
pvReference_V(1) = initial.pv_reference_V;
boostCurrent_A(1) = initial.boost_inductor_current_A;
dcVoltage_V(1) = initial.dc_link_voltage_V;
dutyRatio(1) = initial.duty_ratio;
gridCurrentD_A(1) = initial.grid_current_d_A;
gridCurrentQ_A(1) = initial.grid_current_q_A;

boostIntegrator = 0.0;
vdcIntegrator_A = 0.0;
currentIntegratorD_V = 0.0;
currentIntegratorQ_V = 0.0;
previousMpptVoltage_V = pvVoltage_V(1);
firstCurve = referenceCurves{1};
pvCurrent_A(1) = arrayCurrentAtVoltage(firstCurve, pvVoltage_V(1), sizing);
pvPower_W(1) = pvVoltage_V(1) * pvCurrent_A(1);
previousMpptPower_W = pvPower_W(1);

for sampleIndex = 1:sampleCount - 1
    activeCurve = referenceCurves{curveIndex(sampleIndex)};
    arrayVoc_V = activeCurve.Voc_V * sizing.series_module_count;
    pvCurrent_A(sampleIndex) = arrayCurrentAtVoltage( ...
        activeCurve, pvVoltage_V(sampleIndex), sizing);
    pvPower_W(sampleIndex) = pvVoltage_V(sampleIndex) * pvCurrent_A(sampleIndex);

    if sampleIndex > 1 && mod(sampleIndex - 1, mpptUpdateSamples) == 0
        pvReference_V(sampleIndex) = po_mppt_step( ...
            pvVoltage_V(sampleIndex), pvCurrent_A(sampleIndex), ...
            previousMpptVoltage_V, previousMpptPower_W, ...
            pvReference_V(sampleIndex), ...
            mppt.perturb_step_V * sizing.series_module_count, ...
            mppt.mppt_power_tolerance_W * sizing.total_module_count, ...
            mppt.mppt_voltage_tolerance_V * sizing.series_module_count, ...
            system.minimum_pv_voltage_V, 0.995 * arrayVoc_V);
        previousMpptVoltage_V = pvVoltage_V(sampleIndex);
        previousMpptPower_W = pvPower_W(sampleIndex);
    end

    boostFeedforwardDuty = 1 - pvVoltage_V(sampleIndex) / ...
        max(dcVoltage_V(sampleIndex), system.minimum_dc_voltage_V);
    boostVoltageError_V = pvVoltage_V(sampleIndex) - pvReference_V(sampleIndex);
    [dutyRatio(sampleIndex), boostIntegrator] = pv_voltage_controller( ...
        boostVoltageError_V, boostFeedforwardDuty, boostIntegrator, ...
        boost.kp_pv_voltage_per_V, boost.ki_pv_voltage_per_Vs, ...
        system.sample_time_s, boost.duty_min, boost.duty_max);
    boostOutputPower_W(sampleIndex) = dcVoltage_V(sampleIndex) * ...
        (1 - dutyRatio(sampleIndex)) * boostCurrent_A(sampleIndex);

    [gridCurrentDReference_A(sampleIndex), vdcIntegrator_A] = ...
        dc_link_voltage_controller(dcVoltage_V(sampleIndex), ...
        inverter.dc_link_voltage_ref_V, boostOutputPower_W(sampleIndex), ...
        gridVoltageD_V, vdcIntegrator_A, inverter.vdc_kp_A_per_V, ...
        inverter.vdc_ki_A_per_Vs, system.sample_time_s, ...
        inverter.id_ref_min_A, inverter.id_ref_max_A);

    [inverterVoltageD_V(sampleIndex), inverterVoltageQ_V(sampleIndex), ...
        currentIntegratorD_V, currentIntegratorQ_V, ...
        modulationMagnitude(sampleIndex), inverterVoltageSaturated(sampleIndex)] = ...
        dq_current_controller(gridCurrentD_A(sampleIndex), ...
        gridCurrentQ_A(sampleIndex), gridCurrentDReference_A(sampleIndex), ...
        gridCurrentQReference_A(sampleIndex), gridVoltageD_V, gridVoltageQ_V, ...
        dcVoltage_V(sampleIndex), currentIntegratorD_V, currentIntegratorQ_V, ...
        inverter.current_kp_V_per_A, inverter.current_ki_V_per_As, ...
        system.sample_time_s, omega_rad_s, inverter.filter_inductance_H, ...
        inverter.filter_resistance_ohm, inverter.modulation_index_max);

    [gridActivePower_W(sampleIndex), gridReactivePower_var(sampleIndex)] = ...
        calculate_three_phase_power(gridVoltageD_V, gridVoltageQ_V, ...
        gridCurrentD_A(sampleIndex), gridCurrentQ_A(sampleIndex));
    inverterDcPower_W(sampleIndex) = 1.5 * ...
        (inverterVoltageD_V(sampleIndex) * gridCurrentD_A(sampleIndex) + ...
        inverterVoltageQ_V(sampleIndex) * gridCurrentQ_A(sampleIndex));

    pvVoltageDerivative_Vs = (pvCurrent_A(sampleIndex) - ...
        boostCurrent_A(sampleIndex)) / boost.pv_input_capacitance_F;
    boostCurrentDerivative_As = (pvVoltage_V(sampleIndex) - ...
        (1 - dutyRatio(sampleIndex)) * dcVoltage_V(sampleIndex)) / ...
        boost.boost_inductance_H;
    dcVoltageDerivative_Vs = ((1 - dutyRatio(sampleIndex)) * ...
        boostCurrent_A(sampleIndex) - inverterDcPower_W(sampleIndex) / ...
        max(dcVoltage_V(sampleIndex), system.minimum_dc_voltage_V)) / ...
        inverter.dc_link_capacitance_F;
    gridCurrentDDerivative_As = (inverterVoltageD_V(sampleIndex) - ...
        gridVoltageD_V - inverter.filter_resistance_ohm * ...
        gridCurrentD_A(sampleIndex) + omega_rad_s * ...
        inverter.filter_inductance_H * gridCurrentQ_A(sampleIndex)) / ...
        inverter.filter_inductance_H;
    gridCurrentQDerivative_As = (inverterVoltageQ_V(sampleIndex) - ...
        gridVoltageQ_V - inverter.filter_resistance_ohm * ...
        gridCurrentQ_A(sampleIndex) - omega_rad_s * ...
        inverter.filter_inductance_H * gridCurrentD_A(sampleIndex)) / ...
        inverter.filter_inductance_H;

    pvVoltage_V(sampleIndex + 1) = min(max(pvVoltage_V(sampleIndex) + ...
        system.sample_time_s * pvVoltageDerivative_Vs, ...
        system.minimum_pv_voltage_V), arrayVoc_V);
    boostCurrent_A(sampleIndex + 1) = max(boostCurrent_A(sampleIndex) + ...
        system.sample_time_s * boostCurrentDerivative_As, 0.0);
    dcVoltage_V(sampleIndex + 1) = max(dcVoltage_V(sampleIndex) + ...
        system.sample_time_s * dcVoltageDerivative_Vs, ...
        system.minimum_dc_voltage_V);
    gridCurrentD_A(sampleIndex + 1) = gridCurrentD_A(sampleIndex) + ...
        system.sample_time_s * gridCurrentDDerivative_As;
    gridCurrentQ_A(sampleIndex + 1) = gridCurrentQ_A(sampleIndex) + ...
        system.sample_time_s * gridCurrentQDerivative_As;

    pvReference_V(sampleIndex + 1) = pvReference_V(sampleIndex);
    dutyRatio(sampleIndex + 1) = dutyRatio(sampleIndex);
    if mod(sampleIndex, system.state_check_period_samples) == 0
        validate_integrated_states(sampleIndex, pvVoltage_V(sampleIndex + 1), ...
            boostCurrent_A(sampleIndex + 1), dcVoltage_V(sampleIndex + 1), ...
            gridCurrentD_A(sampleIndex + 1), gridCurrentQ_A(sampleIndex + 1), system);
    end
end
finalCurve = referenceCurves{curveIndex(end)};
pvCurrent_A(end) = arrayCurrentAtVoltage(finalCurve, pvVoltage_V(end), sizing);
pvPower_W(end) = pvVoltage_V(end) * pvCurrent_A(end);
boostOutputPower_W(end) = boostOutputPower_W(end - 1);
gridCurrentDReference_A(end) = gridCurrentDReference_A(end - 1);
inverterVoltageD_V(end) = inverterVoltageD_V(end - 1);
inverterVoltageQ_V(end) = inverterVoltageQ_V(end - 1);
inverterDcPower_W(end) = inverterDcPower_W(end - 1);
modulationMagnitude(end) = modulationMagnitude(end - 1);
inverterVoltageSaturated(end) = inverterVoltageSaturated(end - 1);
[gridActivePower_W(end), gridReactivePower_var(end)] = ...
    calculate_three_phase_power(gridVoltageD_V, gridVoltageQ_V, ...
    gridCurrentD_A(end), gridCurrentQ_A(end));

zeroSequence = zeros(sampleCount, 1);
gridVoltageDVector_V = repmat(gridVoltageD_V, sampleCount, 1);
[gridVoltageA_V, gridVoltageB_V, gridVoltageC_V] = dq_to_abc( ...
    gridVoltageDVector_V, zeroSequence, zeroSequence, gridAngle_rad);
[gridCurrentA_A, gridCurrentB_A, gridCurrentC_A] = dq_to_abc( ...
    gridCurrentD_A, gridCurrentQ_A, zeroSequence, gridAngle_rad);

summary = calculateMetrics(time_s, irradiance_Wm2, theoreticalPmpp_W, ...
    pvPower_W, pvVoltage_V, pvReference_V, dcVoltage_V, ...
    gridActivePower_W, gridReactivePower_var, inverter, system);

simulation = struct("time_s", time_s, "temperature_C", system.temperature_C, ...
    "irradiance_Wm2", irradiance_Wm2, "pv_voltage_V", pvVoltage_V, ...
    "pv_reference_V", pvReference_V, "pv_current_A", pvCurrent_A, ...
    "pv_power_W", pvPower_W, "theoretical_vmpp_V", theoreticalVmpp_V, ...
    "theoretical_pmpp_W", theoreticalPmpp_W, "duty_ratio", dutyRatio, ...
    "boost_inductor_current_A", boostCurrent_A, ...
    "boost_output_power_W", boostOutputPower_W, ...
    "dc_link_voltage_V", dcVoltage_V, ...
    "dc_link_reference_V", repmat(inverter.dc_link_voltage_ref_V, sampleCount, 1), ...
    "inverter_dc_power_W", inverterDcPower_W, ...
    "grid_current_d_A", gridCurrentD_A, ...
    "grid_current_d_reference_A", gridCurrentDReference_A, ...
    "grid_current_q_A", gridCurrentQ_A, ...
    "grid_current_q_reference_A", gridCurrentQReference_A, ...
    "modulation_magnitude", modulationMagnitude, ...
    "inverter_voltage_saturated", inverterVoltageSaturated, ...
    "grid_voltage_a_V", gridVoltageA_V, "grid_voltage_b_V", gridVoltageB_V, ...
    "grid_voltage_c_V", gridVoltageC_V, "grid_current_a_A", gridCurrentA_A, ...
    "grid_current_b_A", gridCurrentB_A, "grid_current_c_A", gridCurrentC_A, ...
    "grid_active_power_W", gridActivePower_W, ...
    "grid_reactive_power_var", gridReactivePower_var, "summary", summary);
end

function validateParameters(system, boost, inverter)
if system.sample_time_s <= 0 || system.simulation_time_s <= 0
    error("STEP6:InvalidTime", "Simulation and sample times must be positive.");
end
if abs(round(system.mppt_update_period_s / system.sample_time_s) * ...
        system.sample_time_s - system.mppt_update_period_s) > ...
        10*eps(system.mppt_update_period_s)
    error("STEP6:InvalidMpptPeriod", ...
        "MPPT period must be an integer multiple of sample time.");
end
if numel(system.irradiance_transition_times_s) ~= ...
        numel(system.irradiance_levels_Wm2) + 1 || ...
        system.irradiance_transition_times_s(1) ~= 0 || ...
        any(diff(system.irradiance_transition_times_s) <= 0) || ...
        system.irradiance_transition_times_s(end) ~= system.simulation_time_s
    error("STEP6:InvalidIrradianceProfile", ...
        "Irradiance transitions must span the simulation.");
end
if boost.duty_min < 0 || boost.duty_max >= 1 || ...
        boost.duty_min >= boost.duty_max
    error("STEP6:InvalidDutyLimits", "Duty limits must satisfy 0 <= min < max < 1.");
end
if inverter.modulation_index_max <= 0 || inverter.modulation_index_max > 1
    error("STEP6:InvalidModulationLimit", ...
        "modulation_index_max must be in (0, 1].");
end
end

function current_A = arrayCurrentAtVoltage(curve, arrayVoltage_V, sizing)
moduleVoltage_V = min(max(arrayVoltage_V / sizing.series_module_count, 0), ...
    curve.Voc_V);
moduleCurrent_A = interp1(curve.voltage_V, curve.current_A, ...
    moduleVoltage_V, "linear", 0);
current_A = max(moduleCurrent_A, 0) * sizing.parallel_string_count;
end

function [irradiance, curveIndex, vmpp, pmpp] = buildReferenceSignals( ...
    time_s, curves, sizing, system)
sampleCount = numel(time_s);
segmentCount = numel(system.irradiance_levels_Wm2);
irradiance = zeros(sampleCount, 1); curveIndex = zeros(sampleCount, 1);
vmpp = zeros(sampleCount, 1); pmpp = zeros(sampleCount, 1);
for segmentIndex = 1:segmentCount
    start_s = system.irradiance_transition_times_s(segmentIndex);
    end_s = system.irradiance_transition_times_s(segmentIndex + 1);
    if segmentIndex < segmentCount
        mask = time_s >= start_s & time_s < end_s;
    else
        mask = time_s >= start_s & time_s <= end_s;
    end
    irradiance(mask) = system.irradiance_levels_Wm2(segmentIndex);
    curveIndex(mask) = segmentIndex;
    vmpp(mask) = curves{segmentIndex}.Vmp_V * sizing.series_module_count;
    pmpp(mask) = curves{segmentIndex}.Pmp_W * sizing.total_module_count;
end
end

function summary = calculateMetrics(time_s, irradiance, theoreticalPower, ...
    pvPower, pvVoltage, pvReference, dcVoltage, gridPower, reactivePower, ...
    inverter, system)
segmentCount = numel(system.irradiance_levels_Wm2);
metrics = zeros(segmentCount, 9);
for segmentIndex = 1:segmentCount
    start_s = system.irradiance_transition_times_s(segmentIndex);
    end_s = system.irradiance_transition_times_s(segmentIndex + 1);
    steadyStart_s = end_s - system.steady_state_fraction * (end_s - start_s);
    if segmentIndex < segmentCount
        mask = time_s >= steadyStart_s & time_s < end_s;
    else
        mask = time_s >= steadyStart_s & time_s <= end_s;
    end
    theoreticalMean_W = mean(theoreticalPower(mask));
    pvMean_W = mean(pvPower(mask));
    gridMean_W = mean(gridPower(mask));
    metrics(segmentIndex, :) = [theoreticalMean_W, pvMean_W, ...
        100*pvMean_W/theoreticalMean_W, mean(pvVoltage(mask)), ...
        mean(pvReference(mask)-pvVoltage(mask)), mean(dcVoltage(mask)), ...
        100*(mean(dcVoltage(mask))-inverter.dc_link_voltage_ref_V) / ...
        inverter.dc_link_voltage_ref_V, gridMean_W, mean(reactivePower(mask))];
end
summary = array2table(metrics, "VariableNames", ["theoretical_pmpp_W", ...
    "average_pv_power_W", "mppt_efficiency_pct", "average_vpv_V", ...
    "vpv_tracking_error_V", "average_vdc_V", "vdc_error_pct", ...
    "average_grid_power_W", "average_reactive_power_var"]);
summary = addvars(summary, system.irradiance_levels_Wm2(:), ...
    100*summary.average_grid_power_W ./ max(summary.average_pv_power_W, eps), ...
    "Before", 1, "NewVariableNames", ...
    ["irradiance_Wm2", "pv_to_grid_power_ratio_pct"]);
end
