%% STEP 6 parameters: integrated approximately 1 MW PV-grid system
% Reuses component/controller settings loaded from STEP 3 through STEP 5.
systemParameters = struct( ...
    "simulation_time_s", 4.0, ...
    "sample_time_s", inverterParameters.sample_time_s, ...
    "temperature_C", 25.0, ...
    "irradiance_levels_Wm2", [600, 1000, 800, 400], ...
    "irradiance_transition_times_s", [0, 1, 2, 3, 4], ...
    "mppt_update_period_s", boostParameters.mppt_update_period_s, ...
    "steady_state_fraction", 0.20, ...
    "iv_voltage_point_count", 500, ...
    "minimum_pv_voltage_V", 100.0, ...
    "minimum_dc_voltage_V", inverterParameters.minimum_dc_voltage_V, ...
    "maximum_dc_voltage_V", 2500.0, ...
    "maximum_boost_current_A", 5000.0, ...
    "maximum_grid_current_A", 4000.0, ...
    "state_check_period_samples", 100);
