function simulation = simulate_grid_inverter(parameters)
%SIMULATE_GRID_INVERTER Simulate an averaged VSI, L filter, and dq control.
%   The grid angle is ideal and the DC input is a prescribed power profile.
%   No PLL, PWM carrier, semiconductor switching, or Boost model is used.

arguments
    parameters (1,1) struct
end
validateParameters(parameters);

time_s = (0:parameters.sample_time_s:parameters.simulation_time_s).';
sampleCount = numel(time_s);
omega_rad_s = 2*pi*parameters.grid_frequency_Hz;
gridAngle_rad = omega_rad_s .* time_s;
gridPhaseRms_V = parameters.grid_voltage_ll_rms_V / sqrt(3);
gridPhasePeak_V = sqrt(2) * gridPhaseRms_V;
gridVoltageD_V = gridPhasePeak_V;
gridVoltageQ_V = 0.0;
dcInputPower_W = buildDcPowerProfile(time_s, parameters);

dcVoltage_V = zeros(sampleCount, 1);
currentD_A = zeros(sampleCount, 1);
currentQ_A = zeros(sampleCount, 1);
referenceD_A = zeros(sampleCount, 1);
referenceQ_A = repmat(parameters.iq_ref_A, sampleCount, 1);
inverterVoltageD_V = zeros(sampleCount, 1);
inverterVoltageQ_V = zeros(sampleCount, 1);
modulationMagnitude = zeros(sampleCount, 1);
voltageSaturated = false(sampleCount, 1);
activePower_W = zeros(sampleCount, 1);
reactivePower_var = zeros(sampleCount, 1);
inverterOutputPower_W = zeros(sampleCount, 1);

dcVoltage_V(1) = parameters.dc_link_voltage_ref_V;
currentD_A(1) = dcInputPower_W(1) / (1.5 * gridVoltageD_V);
currentQ_A(1) = parameters.iq_ref_A;
outerIntegrator_A = 0.0;
currentIntegratorD_V = 0.0;
currentIntegratorQ_V = 0.0;

for sampleIndex = 1:sampleCount - 1
    [referenceD_A(sampleIndex), outerIntegrator_A] = ...
        dc_link_voltage_controller(dcVoltage_V(sampleIndex), ...
        parameters.dc_link_voltage_ref_V, dcInputPower_W(sampleIndex), ...
        gridVoltageD_V, outerIntegrator_A, parameters.vdc_kp_A_per_V, ...
        parameters.vdc_ki_A_per_Vs, parameters.sample_time_s, ...
        parameters.id_ref_min_A, parameters.id_ref_max_A);

    [inverterVoltageD_V(sampleIndex), inverterVoltageQ_V(sampleIndex), ...
        currentIntegratorD_V, currentIntegratorQ_V, ...
        modulationMagnitude(sampleIndex), voltageSaturated(sampleIndex)] = ...
        dq_current_controller(currentD_A(sampleIndex), currentQ_A(sampleIndex), ...
        referenceD_A(sampleIndex), referenceQ_A(sampleIndex), ...
        gridVoltageD_V, gridVoltageQ_V, dcVoltage_V(sampleIndex), ...
        currentIntegratorD_V, currentIntegratorQ_V, ...
        parameters.current_kp_V_per_A, parameters.current_ki_V_per_As, ...
        parameters.sample_time_s, omega_rad_s, ...
        parameters.filter_inductance_H, parameters.filter_resistance_ohm, ...
        parameters.modulation_index_max);

    currentDDerivative_As = (inverterVoltageD_V(sampleIndex) - ...
        gridVoltageD_V - parameters.filter_resistance_ohm * currentD_A(sampleIndex) + ...
        omega_rad_s * parameters.filter_inductance_H * currentQ_A(sampleIndex)) / ...
        parameters.filter_inductance_H;
    currentQDerivative_As = (inverterVoltageQ_V(sampleIndex) - ...
        gridVoltageQ_V - parameters.filter_resistance_ohm * currentQ_A(sampleIndex) - ...
        omega_rad_s * parameters.filter_inductance_H * currentD_A(sampleIndex)) / ...
        parameters.filter_inductance_H;

    [activePower_W(sampleIndex), reactivePower_var(sampleIndex)] = ...
        calculate_three_phase_power(gridVoltageD_V, gridVoltageQ_V, ...
        currentD_A(sampleIndex), currentQ_A(sampleIndex));
    inverterOutputPower_W(sampleIndex) = 1.5 * ...
        (inverterVoltageD_V(sampleIndex) * currentD_A(sampleIndex) + ...
        inverterVoltageQ_V(sampleIndex) * currentQ_A(sampleIndex));
    dcVoltageDerivative_Vs = (dcInputPower_W(sampleIndex) - ...
        inverterOutputPower_W(sampleIndex)) / ...
        (parameters.dc_link_capacitance_F * max(dcVoltage_V(sampleIndex), ...
        parameters.minimum_dc_voltage_V));

    currentD_A(sampleIndex + 1) = currentD_A(sampleIndex) + ...
        parameters.sample_time_s * currentDDerivative_As;
    currentQ_A(sampleIndex + 1) = currentQ_A(sampleIndex) + ...
        parameters.sample_time_s * currentQDerivative_As;
    dcVoltage_V(sampleIndex + 1) = max(dcVoltage_V(sampleIndex) + ...
        parameters.sample_time_s * dcVoltageDerivative_Vs, ...
        parameters.minimum_dc_voltage_V);
end

referenceD_A(end) = referenceD_A(end - 1);
inverterVoltageD_V(end) = inverterVoltageD_V(end - 1);
inverterVoltageQ_V(end) = inverterVoltageQ_V(end - 1);
modulationMagnitude(end) = modulationMagnitude(end - 1);
voltageSaturated(end) = voltageSaturated(end - 1);
[activePower_W(end), reactivePower_var(end)] = calculate_three_phase_power( ...
    gridVoltageD_V, gridVoltageQ_V, currentD_A(end), currentQ_A(end));
inverterOutputPower_W(end) = 1.5 * ...
    (inverterVoltageD_V(end) * currentD_A(end) + ...
    inverterVoltageQ_V(end) * currentQ_A(end));

gridVoltageDVector_V = repmat(gridVoltageD_V, sampleCount, 1);
gridVoltageQVector_V = zeros(sampleCount, 1);
zeroSequence = zeros(sampleCount, 1);
[gridVoltageA_V, gridVoltageB_V, gridVoltageC_V] = dq_to_abc( ...
    gridVoltageDVector_V, gridVoltageQVector_V, zeroSequence, gridAngle_rad);
[gridCurrentA_A, gridCurrentB_A, gridCurrentC_A] = dq_to_abc( ...
    currentD_A, currentQ_A, zeroSequence, gridAngle_rad);

summary = buildSummary(time_s, dcVoltage_V, referenceD_A, currentD_A, ...
    currentQ_A, inverterOutputPower_W, activePower_W, reactivePower_var, ...
    modulationMagnitude, voltageSaturated, dcInputPower_W, parameters);

simulation = struct("time_s", time_s, "grid_angle_rad", gridAngle_rad, ...
    "dc_input_power_W", dcInputPower_W, "dc_voltage_V", dcVoltage_V, ...
    "dc_voltage_reference_V", repmat(parameters.dc_link_voltage_ref_V, sampleCount, 1), ...
    "current_d_A", currentD_A, "current_d_reference_A", referenceD_A, ...
    "current_q_A", currentQ_A, "current_q_reference_A", referenceQ_A, ...
    "inverter_voltage_d_V", inverterVoltageD_V, ...
    "inverter_voltage_q_V", inverterVoltageQ_V, ...
    "modulation_magnitude", modulationMagnitude, ...
    "voltage_saturated", voltageSaturated, ...
    "grid_voltage_a_V", gridVoltageA_V, "grid_voltage_b_V", gridVoltageB_V, ...
    "grid_voltage_c_V", gridVoltageC_V, "grid_current_a_A", gridCurrentA_A, ...
    "grid_current_b_A", gridCurrentB_A, "grid_current_c_A", gridCurrentC_A, ...
    "inverter_output_power_W", inverterOutputPower_W, ...
    "active_power_W", activePower_W, "reactive_power_var", reactivePower_var, ...
    "summary", summary);
end

function validateParameters(p)
if p.sample_time_s <= 0 || p.simulation_time_s <= 0
    error("STEP5:InvalidTime", "Simulation and sample times must be positive.");
end
if p.grid_frequency_Hz <= 0 || p.grid_voltage_ll_rms_V <= 0
    error("STEP5:InvalidGrid", "Grid frequency and line-line RMS voltage must be positive.");
end
if any([p.dc_link_capacitance_F, p.filter_inductance_H] <= 0) || ...
        p.filter_resistance_ohm < 0
    error("STEP5:InvalidPassiveComponent", "C and L must be positive; R cannot be negative.");
end
if p.modulation_index_max <= 0 || p.modulation_index_max > 1
    error("STEP5:InvalidModulationLimit", "modulation_index_max must be in (0, 1].");
end
if numel(p.disturbance_transition_times_s) ~= ...
        numel(p.dc_input_power_levels_W) + 1 || ...
        p.disturbance_transition_times_s(1) ~= 0 || ...
        any(diff(p.disturbance_transition_times_s) <= 0) || ...
        p.disturbance_transition_times_s(end) ~= p.simulation_time_s
    error("STEP5:InvalidDisturbanceProfile", ...
        "Disturbance transitions must span the simulation with increasing times.");
end
if any(p.dc_input_power_levels_W < 0)
    error("STEP5:InvalidDcPower", "DC input power cannot be negative.");
end
end

function dcPower_W = buildDcPowerProfile(time_s, p)
dcPower_W = zeros(size(time_s));
segmentCount = numel(p.dc_input_power_levels_W);
for segmentIndex = 1:segmentCount
    start_s = p.disturbance_transition_times_s(segmentIndex);
    end_s = p.disturbance_transition_times_s(segmentIndex + 1);
    if segmentIndex < segmentCount
        mask = time_s >= start_s & time_s < end_s;
    else
        mask = time_s >= start_s & time_s <= end_s;
    end
    dcPower_W(mask) = p.dc_input_power_levels_W(segmentIndex);
end
end

function summary = buildSummary(time_s, dcVoltage, idReference, id, iq, ...
    inverterPower, activePower, reactivePower, modulation, saturated, dcPower, p)
segmentCount = numel(p.dc_input_power_levels_W);
metrics = zeros(segmentCount, 11);
for segmentIndex = 1:segmentCount
    start_s = p.disturbance_transition_times_s(segmentIndex);
    end_s = p.disturbance_transition_times_s(segmentIndex + 1);
    steadyStart_s = end_s - p.steady_state_fraction * (end_s - start_s);
    if segmentIndex < segmentCount
        mask = time_s >= steadyStart_s & time_s < end_s;
    else
        mask = time_s >= steadyStart_s & time_s <= end_s;
    end
    segmentMask = time_s >= start_s & time_s <= end_s;
    dcPowerMean_W = mean(dcPower(mask));
    inverterPowerMean_W = mean(inverterPower(mask));
    metrics(segmentIndex, :) = [ ...
        mean(dcVoltage(mask)) - p.dc_link_voltage_ref_V, ...
        max(dcVoltage(segmentMask)) - p.dc_link_voltage_ref_V, ...
        mean(idReference(mask) - id(mask)), sqrt(mean(iq(mask).^2)), ...
        dcPowerMean_W, inverterPowerMean_W, mean(activePower(mask)), ...
        mean(reactivePower(mask)), ...
        100 * (inverterPowerMean_W - dcPowerMean_W) / max(dcPowerMean_W, eps), ...
        max(modulation(segmentMask)), 100 * mean(saturated(segmentMask))];
end
summary = array2table(metrics, "VariableNames", [ ...
    "vdc_steady_error_V", "vdc_positive_overshoot_V", ...
    "id_tracking_error_A", "iq_rms_A", "dc_input_power_mean_W", ...
    "inverter_output_power_mean_W", "grid_active_power_mean_W", ...
    "grid_reactive_power_mean_var", "dc_inverter_balance_error_pct", ...
    "modulation_max", "voltage_saturation_pct"]);
summary = addvars(summary, p.dc_input_power_levels_W(:), ...
    "Before", 1, "NewVariableNames", "dc_input_power_W");
end
