%% STEP 5 parameters: averaged grid-side inverter with dq control
inverterParameters = struct( ...
    "grid_frequency_Hz", 60.0, ...
    "grid_voltage_ll_rms_V", 380.0, ...
    "dc_link_voltage_ref_V", 1350.0, ...
    "dc_link_capacitance_F", 0.20, ...
    "filter_inductance_H", 0.30e-3, ...
    "filter_resistance_ohm", 0.020, ...
    "modulation_index_max", 0.95, ...
    "vdc_kp_A_per_V", 8.0, ...
    "vdc_ki_A_per_Vs", 100.0, ...
    "current_kp_V_per_A", 0.90, ...
    "current_ki_V_per_As", 60.0, ...
    "id_ref_min_A", 0.0, ...
    "id_ref_max_A", 2500.0, ...
    "iq_ref_A", 0.0, ...
    "sample_time_s", 20.0e-6, ...
    "simulation_time_s", 1.0, ...
    "disturbance_transition_times_s", [0.0, 0.3, 0.6, 1.0], ...
    "dc_input_power_levels_W", [500.0e3, 800.0e3, 500.0e3], ...
    "steady_state_fraction", 0.20, ...
    "minimum_dc_voltage_V", 100.0);
