%% STEP 4 parameters: averaged Boost Converter and DC-link
boostParameters = struct( ...
    "target_power_W", 1.0e6, ...
    "pv_voltage_nominal_V", 1037.5, ...
    "dc_link_voltage_ref_V", 1350.0, ...
    "boost_inductance_H", 5.0e-3, ...
    "pv_input_capacitance_F", 20.0e-3, ...
    "dc_link_capacitance_F", 50.0e-3, ...
    "duty_min", 0.05, ...
    "duty_max", 0.90, ...
    "kp_pv_voltage_per_V", 2.0e-3, ...
    "ki_pv_voltage_per_Vs", 0.50, ...
    "sample_time_s", 5.0e-5, ...
    "simulation_time_s", 4.0, ...
    "mppt_update_period_s", 0.01, ...
    "irradiance_levels_Wm2", [600, 1000, 800, 400], ...
    "irradiance_transition_times_s", [0, 1, 2, 3, 4], ...
    "temperature_C", 25.0, ...
    "initial_pv_voltage_V", 800.0, ...
    "initial_vref_V", 800.0, ...
    "pv_voltage_min_V", 100.0, ...
    "steady_state_fraction", 0.20, ...
    "iv_voltage_point_count", 500);
