%% STEP 3 parameters: P&O MPPT with a voltage-following plant abstraction
mpptParameters = struct( ...
    "simulation_time_s", 4.0, ...
    "sample_time_s", 0.005, ...
    "temperature_C", 25.0, ...
    "irradiance_levels_Wm2", [600, 1000, 800, 400], ...
    "irradiance_transition_times_s", [0, 1, 2, 3, 4], ...
    "initial_pv_voltage_V", 25.0, ...
    "initial_vref_V", 25.0, ...
    "perturb_step_V", 0.20, ...
    "mppt_power_tolerance_W", 0.02, ...
    "mppt_voltage_tolerance_V", 1.0e-6, ...
    "vref_min_V", 1.0, ...
    "vref_max_V", 49.0, ...
    "plant_response_alpha", 0.25, ...
    "steady_state_fraction", 0.20, ...
    "iv_voltage_point_count", 500);
