function sizing = calculate_pv_array_size(module, targetPower_W, targetDcVoltage_V)
%CALCULATE_PV_ARRAY_SIZE Size series modules and parallel strings.
%   Counts are rounded up so the nominal module ratings meet or exceed both
%   the requested MPP voltage and requested power.

arguments
    module (1,1) struct
    targetPower_W (1,1) double {mustBePositive}
    targetDcVoltage_V (1,1) double {mustBePositive}
end
requiredFields = ["Vmp_ref_V", "Imp_ref_A", "Pmp_ref_W"];
if ~all(isfield(module, requiredFields))
    error("STEP2:MissingSizingParameter", ...
        "Module Vmp_ref_V, Imp_ref_A, and Pmp_ref_W are required.");
end

seriesModuleCount = ceil(targetDcVoltage_V / module.Vmp_ref_V);
parallelStringCount = ceil(targetPower_W / ...
    (seriesModuleCount * module.Pmp_ref_W));
totalModuleCount = seriesModuleCount * parallelStringCount;

nominalArrayPower_W = totalModuleCount * module.Pmp_ref_W;
nominalArrayVmp_V = seriesModuleCount * module.Vmp_ref_V;
nominalArrayImp_A = parallelStringCount * module.Imp_ref_A;

sizing = struct( ...
    "series_module_count", seriesModuleCount, ...
    "parallel_string_count", parallelStringCount, ...
    "total_module_count", totalModuleCount, ...
    "nominal_array_power_W", nominalArrayPower_W, ...
    "nominal_array_Vmp_V", nominalArrayVmp_V, ...
    "nominal_array_Imp_A", nominalArrayImp_A, ...
    "power_sizing_error_percent", ...
        100 * (nominalArrayPower_W - targetPower_W) / targetPower_W, ...
    "voltage_sizing_error_percent", ...
        100 * (nominalArrayVmp_V - targetDcVoltage_V) / targetDcVoltage_V);
end
