%% STEP 2 parameters: generic example PV module and array targets
% These are placeholder engineering parameters, not copied from a specific
% manufacturer datasheet or course material. Replace this section when a
% documented module is selected.

moduleParameters = struct( ...
    "Voc_ref_V", 49.5, ...
    "Isc_ref_A", 13.8, ...
    "Vmp_ref_V", 41.5, ...
    "Imp_ref_A", 13.1, ...
    "Pmp_ref_W", 543.65, ...
    "temperature_coefficient_Voc_per_C", -0.0028, ...
    "temperature_coefficient_Isc_per_C", 0.0005, ...
    "T_ref_C", 25.0, ...
    "G_ref_Wm2", 1000.0, ...
    "series_cell_count", 72, ...
    "diode_ideality_factor", 1.30, ...
    "series_resistance_ohm", 0.25, ...
    "shunt_resistance_ohm", 400.0);

irradiance_conditions_Wm2 = [400, 600, 800, 1000];
temperature_conditions_C = [25, 45];
iv_voltage_point_count = 500;

target_power_W = 1.0e6;
target_dc_voltage_V = 1000.0;
